import Head from 'next/head'
import NavigationBar from '../components/NavigationBar';
import LandingView from '../components/LandingView';
import Footer from '../components/Footer';
import Navbar from '../components/NavBar';

export default function Home({posts}) {
   
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='px-16'  >

            <Navbar/>
            <div className='sm:flex flex-col-2 h-[90vh] sm:gap-10 lg:pl-0 pl-8 bg-black/25'>
                <div className='bg-grill4 bg-cover w-5/12 '>
                </div>
                <div className='px-2 py-5 '> 
                <LandingView />
                </div>
            </div>
            <Footer/>
        </main>
    </>
  )
}
