import Head from 'next/head'
import NavigationBar from '../components/NavigationBar';
import LandingView from '../components/LandingView';
import Footer from '../components/Footer';


export default function Home({posts}) {
   
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='px-16'  >

            <NavigationBar/>
            <div className='flex flex-col-2 h-[90vh] gap-10 '>
                <div className='bg-grill1 bg-cover w-5/12 '>
                </div>
                <div className='px-2 py-5'> 
                <LandingView />
                </div>
            </div>
            <Footer/>
        </main>
    </>
  )
}
