import Head from 'next/head'
import {GraphQLClient, gql} from 'graphql-request'
import NavigationBar from '../components/NavigationBar';
import BlogCard from '../components/BlogCard';
import Footer from '../components/Footer';
const graphcms = new GraphQLClient("https://api-eu-central-1-shared-euc1-02.hygraph.com/v2/clc4i967301ju01ulcopm3cft/master");

const QUERY = gql`
    {
        posts{
            id,
            title,
            category,
            shortDescription,
            slug,
                content{
                    html
                },
                coverPhoto {
                    id,
                    url
                },
                author {
                    id,
                    name,
                    avatar{
                        id,
                        url
                    }
                },
                datePublished
        }
  }
`

export async function getStaticProps(){
    const {posts} = await graphcms.request(QUERY);
    return {
            props:{
                posts,
                },
                revalidate: 10,
        };
    }

export default function Home({posts}) {
   
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='px-16'  >

            <NavigationBar/>
            
     
            <div className='flex flex-row-2 gap-4 '>
                     
                <div className='py-5 '> 
                {posts.map((post) =>(
                    <BlogCard
                    category = {post.category}
                    title ={post.title} 
                    author={post.author} 
                    coverPhoto={post.coverPhoto} 
                    short={post.shortDescription}
                    key={post.id} 
                    datePublished={post.datePublished} 
                    slug={post.slug}  />
                ))}
                </div>
                
                
            </div>
            <Footer/>
              
              
        </main>
    </>
  )
}
